# Generated by Django 5.1.1 on 2025-05-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='KG', max_length=50),
        ),
    ]
